/* tslint:disable */
/* eslint-disable */
/**
 * Income Calculator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiValidateJWTGet200Response,
  ApiValidateJWTGet401Response,
} from '../models/index';
import {
    ApiValidateJWTGet200ResponseFromJSON,
    ApiValidateJWTGet200ResponseToJSON,
    ApiValidateJWTGet401ResponseFromJSON,
    ApiValidateJWTGet401ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Validates the user\'s JSON Web Token
     */
    async apiValidateJWTGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiValidateJWTGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/validateJWT`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiValidateJWTGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Validates the user\'s JSON Web Token
     */
    async apiValidateJWTGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiValidateJWTGet200Response> {
        const response = await this.apiValidateJWTGetRaw(initOverrides);
        return await response.value();
    }

}
