version: "3.9"

# Adding comment for testing

services:
    db:
        image: postgres
        container_name: db
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - productionpgdata:/var/lib/postgresql/data
        networks:
            - app-network
        restart: unless-stopped

    backend:
        image: ghcr.io/${GITHUB_REPO}/backend:latest
        container_name: ${API_CONTAINER_NAME}
        depends_on:
            - db
        environment:
            DATABASE_URL: ${DATABASE_URL}
            PORT: ${API_PORT}
            JWT_KEY: ${JWT_KEY}
            NODE_ENV: ${NODE_ENV}
            EMAIL_HOST: ${EMAIL_HOST}
            EMAIL_PORT: ${EMAIL_PORT}
            EMAIL_SECURE: ${EMAIL_SECURE}
            EMAIL_PASSWORD: ${EMAIL_PASSWORD}
        ports:
            - "${API_PORT}:${API_PORT}"
        restart: unless-stopped
        networks:
            - app-network

networks:
    app-network:
        name: ${DOCKER_NETWORK_NAME}

volumes:
    productionpgdata:
