/* tslint:disable */
/* eslint-disable */
/**
 * Income Calculator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTransactionInput
 */
export interface UpdateTransactionInput {
    /**
     * 
     * @type {string}
     * @memberof UpdateTransactionInput
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTransactionInput
     */
    isExpense: boolean;
    /**
     * 
     * @type {number}
     * @memberof UpdateTransactionInput
     */
    amountInPence: number;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTransactionInput
     */
    isRecurring: boolean;
    /**
     * 
     * @type {Date}
     * @memberof UpdateTransactionInput
     */
    startDate: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateTransactionInput
     */
    finishDate: Date | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTransactionInput
     */
    recurrenceType: UpdateTransactionInputRecurrenceTypeEnum | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateTransactionInput
     */
    recurrenceRate: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateTransactionInput
     */
    specificDayOfWeek: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateTransactionInput
     */
    specificDayOfMonth: number | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTransactionInput
     */
    firstLastDayOfMonth: UpdateTransactionInputFirstLastDayOfMonthEnum | null;
}


/**
 * @export
 */
export const UpdateTransactionInputRecurrenceTypeEnum = {
    Day: 'day',
    Week: 'week',
    Month: 'month',
    Year: 'year'
} as const;
export type UpdateTransactionInputRecurrenceTypeEnum = typeof UpdateTransactionInputRecurrenceTypeEnum[keyof typeof UpdateTransactionInputRecurrenceTypeEnum];

/**
 * @export
 */
export const UpdateTransactionInputFirstLastDayOfMonthEnum = {
    FirstBusiness: 'first_business',
    LastBusiness: 'last_business',
    Last: 'last',
    Specific: 'specific'
} as const;
export type UpdateTransactionInputFirstLastDayOfMonthEnum = typeof UpdateTransactionInputFirstLastDayOfMonthEnum[keyof typeof UpdateTransactionInputFirstLastDayOfMonthEnum];


/**
 * Check if a given object implements the UpdateTransactionInput interface.
 */
export function instanceOfUpdateTransactionInput(value: object): value is UpdateTransactionInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('isExpense' in value) || value['isExpense'] === undefined) return false;
    if (!('amountInPence' in value) || value['amountInPence'] === undefined) return false;
    if (!('isRecurring' in value) || value['isRecurring'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('finishDate' in value) || value['finishDate'] === undefined) return false;
    if (!('recurrenceType' in value) || value['recurrenceType'] === undefined) return false;
    if (!('recurrenceRate' in value) || value['recurrenceRate'] === undefined) return false;
    if (!('specificDayOfWeek' in value) || value['specificDayOfWeek'] === undefined) return false;
    if (!('specificDayOfMonth' in value) || value['specificDayOfMonth'] === undefined) return false;
    if (!('firstLastDayOfMonth' in value) || value['firstLastDayOfMonth'] === undefined) return false;
    return true;
}

export function UpdateTransactionInputFromJSON(json: any): UpdateTransactionInput {
    return UpdateTransactionInputFromJSONTyped(json, false);
}

export function UpdateTransactionInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTransactionInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'isExpense': json['isExpense'],
        'amountInPence': json['amountInPence'],
        'isRecurring': json['isRecurring'],
        'startDate': (json['startDate'] == null ? null : new Date(json['startDate'])),
        'finishDate': (json['finishDate'] == null ? null : new Date(json['finishDate'])),
        'recurrenceType': json['recurrenceType'],
        'recurrenceRate': json['recurrenceRate'],
        'specificDayOfWeek': json['specificDayOfWeek'],
        'specificDayOfMonth': json['specificDayOfMonth'],
        'firstLastDayOfMonth': json['firstLastDayOfMonth'],
    };
}

export function UpdateTransactionInputToJSON(value?: UpdateTransactionInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'isExpense': value['isExpense'],
        'amountInPence': value['amountInPence'],
        'isRecurring': value['isRecurring'],
        'startDate': (value['startDate'] == null ? null : (value['startDate'] as any).toISOString()),
        'finishDate': (value['finishDate'] == null ? null : (value['finishDate'] as any).toISOString()),
        'recurrenceType': value['recurrenceType'],
        'recurrenceRate': value['recurrenceRate'],
        'specificDayOfWeek': value['specificDayOfWeek'],
        'specificDayOfMonth': value['specificDayOfMonth'],
        'firstLastDayOfMonth': value['firstLastDayOfMonth'],
    };
}

